version: "3.8"

services:
  app:
    container_name: laravel_app_demo
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_VERSION=${COMPOSER_VERSION}
    image: laravel_app_demo:1.0
    restart: always
    ports:
      - ${DOCKER_HOST}:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - general

  database:
    container_name: laravel_app_db_demo
    image: mariadb:${MARIADB_VERSION}
    restart: always
    ports:
      - ${DOCKER_DB_HOST}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - general

networks:
  general:
    name: general_net

volumes:
  db_data:
