version: "3"

services:
  app:
    container_name: app
    build: .
    image: laravel-app-demo:latest
    restart: always
    ports:
      - ${APP_HOST:-80}:80
      - ${MCP_PORT:-5137}:5137
    volumes:
<<<<<<< HEAD
      - .:/var/www/html
      - /var/www/html/vendor
=======
      - ./:/var/www/html          # código en vivo
      - vendor_cache:/var/www/html/vendor        # vendor dentro del contenedor
>>>>>>> 660d5f8 (feature/RI-468: Mount with entrypoint sh)
      - app_data:/data
    depends_on:
      - database

  database:
    container_name: database
    image: mariadb:${MARIADB_VERSION:-10.8.3}
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    container_name: mailhog-laravel-app
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  db_data:
  app_data:
  vendor_cache:
