version: "3"

services:
  app:
    container_name: app
    build: .
    image: laravel_app_demo:1.0
    restart: always
    ports:
      - ${APP_HOST:-80}:80
    volumes:
        - app_data:/var/www/html/storage
    depends_on:
        - database

  database:
    container_name: database
    image: mariadb:${MARIADB_VERSION:-10.8.3}
    restart: always
    ports:
      - ${DB_HOST:-127.0.0.1:3306}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_data:
