apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-app-demo
  namespace: demos
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
  selector:
    matchLabels:
      type: laravel-app-demo
