apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume
  labels:
    type: shared-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/shared-volume"
