name: Workflow to push to Nexus Server InOffice

on:
  push:
    branches:
      - feature/RI-1692

jobs:
  Push-To-Nexus-Server-InOffice:
    runs-on: ubuntu-latest

    steps:
      - name: Zerotier Configuration
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ vars.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Ping to Nexus Sever InOffice
        shell: bash
        run: |
          count=20
          while ! ping -c 3 ${{ vars.NEXUS_IP_SERVER }} ; do
            echo "waiting..." ;
            sleep 5 ;
            let count=count-1
          done
          echo "success ping connection to server inOffice ${{ vars.NEXUS_IP_SERVER }}"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{ vars.NEXUS_IP_SERVER }}:${{ vars.NEXUS_PORT }}"]
              http = true
              insecure = true

      - name: Login to the Artifact repository
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.NEXUS_IP_SERVER }}:${{ vars.NEXUS_PORT }}
          username: ${{ vars.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}            

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_IMAGE }}:latest
