name: Workflow to push to Nexus Server InOffice

on:
  push:
    branches:
      - feature/RI-1692

jobs:
  Push-Nexus-Server-InOffice:
    runs-on: ubuntu-latest

    steps:
      - name: Zerotier Configuration
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ vars.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Ping to Nexus Sever InOffice
        shell: bash
        run: |
          count=3
          while ! ping -c 3 ${{ vars.NEXUS_IP_SERVER }} ; do
            echo "waiting..." ;
            sleep 1 ;
            let count=count-1
          done
          echo "success ping connection to server inOffice ${{ vars.NEXUS_IP_SERVER }}"

      - name: Checkout Repository
        uses: actions/checkout@v3    


      - name: Install and Set up Docker on Runner 
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo mkdir -m 0755 -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$(lsb_release -i | awk '{ print tolower($3) }') $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce-cli docker-buildx-plugin docker-compose-plugin

      - name: Set up Docker daemon.json
        run: |
          echo '{"insecure-registries": ["${{ vars.NEXUS_IP_SERVER }}:${{vars.NEXUS_PORT}}"]}' | sudo tee /etc/docker/daemon.json

      - name: Restart Docker
        run: sudo systemctl restart docker

      - name: Verify Docker Configuration
        run: cat /etc/docker/daemon.json

      - name: Build Docker image from this Repository 
        shell: bash
        run: |
          docker build -t laravel-app-demo --build-arg APP_URL="http://my-domain.com" --no-cache .

      - name: Docker login into Nexus Repository server
        run: |
          echo '${{ secrets.NEXUS_PASSWORD }}' | docker login -u '${{ vars.NEXUS_USERNAME }}' --password-stdin ${{ vars.NEXUS_IP_SERVER }}:${{vars.NEXUS_PORT}}

      - name: Tag Docker image with latest
        run: |
          docker tag laravel-app-demo ${{ vars.NEXUS_IP_SERVER }}:${{vars.NEXUS_PORT}}/nexus/docker/laravel-app-demo/staging/laravel-app-demo:latest

      - name: Push Docker image to Nexus Repository
        run: |
          docker push ${{ vars.NEXUS_IP_SERVER }}:${{vars.NEXUS_PORT}}/nexus/docker/laravel-app-demo/staging/laravel-app-demo:latest

